apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
data:
{{- range $k, $v := .Values.global.files }}
  {{ $k | replace "_dot_" "." }}: |-
{{ $v | indent 4 }}
{{- end }}
