# Short name for this collection of services
domain:
# location where these IOCs and services will run
location:
# sizes of the auto provisioned PVs
opiSize: 1Gi
runtimeSize: 1Gi
autosaveSize: 1Gi
binariesSize: 1Gi
