# @schema additionalProperties: true
global:
  # @schema  $ref:$k8s/container.json#/properties/env
  env: []

# @schema description: Short name for this collection of services
domain:
# @schema description: location where these IOCs and services will run
location:
# @schema description: sizes of the auto provisioned PVs
opiSize: 1Gi
runtimeSize: 1Gi
autosaveSize: 1Gi
binariesSize: 1Gi

# @schema  $ref:$k8s/container.json#/properties/env
env: []
